version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          CC_TEST_REPORTER_ID: 'f9b0472297534abf2d3fcc2cb42d318b7af1df3954bed7cf5f98aa12391314e8'
    steps:
      - checkout
      # Download test-reporter
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: bundle install --path vendor/bundle
      - run: |
          ./cc-test-reporter before-build
          bundle exec rspec
          ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
